{
    "name": "Contoso Realistic Demo",
    "summary": "Installs the applications used by the Contoso end-to-end demo",
    "version": "18.0.1.0.0",
    "category": "Tools",
    "license": "LGPL-3",
    "depends": [
        "contacts",
        "crm",
        "sale_management",
        "purchase",
        "stock",
        "account",
        "project",
        "hr",
        "hr_expense",
        "hr_timesheet",
        "maintenance",
        "fleet",
        "mrp",
        "website_sale",
        "point_of_sale",
    ],
    "installable": True,
    "application": False,
}
